export const s = {
  container:
    "px-8 sm:px-14 2xl:px-16 pt-10 pb-20 grid place-items-center w-full relative text-primary-light dark:text-primary-dark",
  landing: "pt-40 xl:pt-48",
  title: "text-center mb-16 md:mb-[5rem]",
  h1title: "text-5xl sm:text-6xl font-bold",
  h2title: "text-5xl font-bold",
  h2titleH: "text-5xl font-semibold",
  h3title: "text-4xl font-bold",
  h4title: "text-3xl font-bold",
  h5title: "text-2xl font-bold",
  h6title: "text-xl font-bold",
  h6titleM: "text-xl font-medium",
  h7titleM: "text-xl font-medium",
  h7titleUpper: "text-xl font-medium uppercase",
  p0medium: "text-4xl font-medium",
  p0bold: "text-4xl font-bold",
  p1medium: "text-2xl font-medium",
  p1heavy: "text-2xl font-semibold",
  p2heavy: "text-xl font-semibold",
  p2book: "text-xl font-normal",
  p2medium: "text-xl font-medium",
  p3heavy: "text-lg font-semibold",
  p3book: "text-lg font-normal",
  p3medium: "text-lg font-medium",
  p4medium: "text-base font-medium",
  p4book: "text-base font-normal",
  p5medium: "text-sm font-medium",
  p5book: "text-sm font-normal",
  text: "text-base text-secondary-light dark:text-secondary-dark",
  serviceBox: "p-8 lg:min-w-[26.875rem] box1",
  serviceBox2: "p-8 lg:min-w-[26.875rem] box1",
  bgImage: "bg-center bg-no-repeat bg-cover",
  image: "bg-center bg-no-repeat bg-contain",
  input:
    "w-full box2 p-4 border border-l-0 border-[#E0E0E0] focus:outline-none dark:border-[#282B42]",
  inputIcon:
    "border rounded-tl-2xl rounded-bl-2xl border-[#E0E0E0] dark:border-[#282B42] box-content bg-origin-content p-[1.125rem]",
};
